// Bảng tra mã thiệp -> tên khách mời (mã ngẫu nhiên, không lộ tên trong URL).
export const GUESTS: Record<string, string> = {
  "5inv9s": "Lê Hồng Sơn",
  "7avqmf": "Trần Đức Tài",
  "ge4jdi": "Nguyễn Thị Lâm",
  "qt8a3w": "Thái Danh Phương",
  "w4cu4q": "Tôn Đức Hưng",
  "bxmyud": "Lê Văn Định",
  "3uadii": "Trần Đình Thuận",
  "vhk4tb": "Phan Quyết Thắng",
  "pv8e4w": "Ngô Đức Việt",
  "9pwx9d": "Phan Thị Bích Liên",
  "mfj49b": "Nguyễn Khánh Nam",
  "r7v5qd": "Nguyễn Công Hoàn",
  "pzps77": "Trần Văn Kháng",
  "6svgzh": "Hồ Trung Sơn",
  "54a2sj": "Lê Minh Đức",
  "t4gtjr": "Phan Vĩnh Thi",
  "mg6fwq": "Hoàng Văn Nam",
  "mnjgna": "Nguyễn Thị Bông",
  "ch8eaz": "Trần Anh Sơn",
  "t9rmzj": "Phan Xuân Diệu",
  "vcby3u": "Nguyễn Hữu Dũng",
  "yqerqi": "Nguyễn Thị Thúy",
  "d66mmi": "Nguyễn Thị Như Ý",
  "dqy7uh": "Đinh Thị Quế",
  "bjhpbf": "Lê Thị Sen",
  "jgvjka": "Trần Văn Hải",
  "bw7yhz": "Thân Thị Hòa",
  "5qz8rc": "Nguyễn Thị Thu Hiên",
  "4n67vc": "Chu Thị Lộc An",
  "v2w8gh": "Bùi Thị Thanh",
  "c5xpnm": "Trần Đình Hưng",
  "kdh56f": "Nguyễn Thị Thu Hương",
  "he8kdv": "Lê Thị Thanh Hằng",
  "zharre": "Thái Thị Hiền",
  "2p8hz3": "Nguyễn Thị Kim Hoa",
  "yfbk4r": "Nguyễn Thị Vinh",
  "6mpe4j": "Nguyễn Công Sâm",
  "3tt2t9": "Phạm Thị Hà An",
  "3kc2mt": "Nguyễn Thị Thanh Huyền",
  "r86x5u": "Trần Thị Lệ Hằng",
  "25bpva": "Lê Thị Hải Yến",
  "3ehc68": "Nguyễn Thị Việt Hà",
  "tazu5r": "Đinh Thị Bảo Giang",
  "rngifz": "Nguyễn Thị Phương Nga",
  "xzpzd3": "Phạm Thị Hồng Lĩnh",
  "3mhqyr": "Nguyễn Thanh Bình",
  "9388t3": "Nguyễn Thị Vinh",
  "qvisfk": "Trịnh Thị Kiều Hoa",
  "49egwy": "Nguyễn Thị Thanh Nga",
  "ekibhg": "Hoàng Ngọc Thúy",
  "2tfxz5": "Nguyễn Thị Mỹ Thanh",
  "th4tzm": "Phan Thị Thu Hiền",
  "3esxeu": "Nguyễn Thị Huế",
  "uursdc": "Phạm Văn Chí",
  "pwwbsd": "Phạm Đức Thiện",
  "q5vmds": "Nguyễn Phú Quốc",
  "tuwene": "Đặng Văn Toàn",
  "km2s58": "Ngô Đức Chính",
  "33j6gd": "Nguyễn Hồng Sơn",
  "ztxqku": "Nguyễn Viết Hải",
};
